"""Fix VARCHAR length issue

Revision ID: ebecad99f3cf
Revises: 
Create Date: 2024-07-29 17:15:32.390296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ebecad99f3cf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense_splits', 'expense_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('expense_splits', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('expense_splits', 'split_type',
               existing_type=mysql.ENUM('equal', 'exact', 'percentage'),
               nullable=True)
    op.create_index(op.f('ix_expense_splits_id'), 'expense_splits', ['id'], unique=False)
    op.drop_constraint('expense_splits_ibfk_1', 'expense_splits', type_='foreignkey')
    op.drop_constraint('expense_splits_ibfk_2', 'expense_splits', type_='foreignkey')
    op.create_foreign_key(None, 'expense_splits', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'expense_splits', 'expenses', ['expense_id'], ['id'])
    op.alter_column('expenses', 'description',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('expenses', 'payer_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.drop_constraint('expenses_ibfk_1', 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['payer_id'], ['id'])
    op.alter_column('users', 'mobile_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'mobile_number',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key('expenses_ibfk_1', 'expenses', 'users', ['payer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.alter_column('expenses', 'payer_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('expenses', 'description',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'expense_splits', type_='foreignkey')
    op.drop_constraint(None, 'expense_splits', type_='foreignkey')
    op.create_foreign_key('expense_splits_ibfk_2', 'expense_splits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('expense_splits_ibfk_1', 'expense_splits', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_expense_splits_id'), table_name='expense_splits')
    op.alter_column('expense_splits', 'split_type',
               existing_type=mysql.ENUM('equal', 'exact', 'percentage'),
               nullable=False)
    op.alter_column('expense_splits', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('expense_splits', 'expense_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
